### ISSUE TITLE
Using Resource Router with Publisher

### ISSUE THREAD

**Issue by siebird** [rsanchez/resource_router#18]
Rob, I just ran into an issue with RR & Publisher on routes for secondary languages. I think this might be due to Publisher saving all data in `exp_publisher_*` tables instead of the native tables. Is it possible to that RR works with Publisher? 

```
':any|es/:any' => function($router, $wildcard) {
		$landing = array('status' => 'Open', 'channel_id' => 14);
		$confirm = array('status' => 'Open', 'channel_id' => 16);

		// is the current page a landing page?
		if ($wildcard->isValidUrlTitle($landing)) {
			$router->setTemplate('site/landing_page');
		// is the current page a confirmation page
		} else if ($wildcard->isValidUrlTitle($confirm)) {
			$router->setTemplate('site/confirm_page');
		}
	}
```

**Comment by siebird** [comment]
Thanks for the example, it helps to see how to format properly. I updated the query a little for my needs as the site only has one secondary language. However, the conditional for the routing seems to not work.  Am I set the `$result` variable correctly or is the conditional not formatted properly?

```
'es/:any' => function($router, $wildcard) {
	$query = ee()->db->select('channel_id')
		->where('site_id', 1)
		->where('url_title', $wildcard->value)
		->where('publisher_status', 'open')
		->get('publisher_titles');

	$result = $query->row('channel_id');

	// is the current page a landing page?
	if ($result == 14) {
		$router->setTemplate('site/landing_page');
	// is the current page a confirmation page
	} else if ($query == 16) {
		$router->setTemplate('site/confirm_page');
	}
}```

**Comment by rsanchez** [comment]
It's hard to say. I'd try `var_dump($result)` or `var_dump($query->result())` to see if your query is getting the right data.

**Comment by siebird** [comment]
I found the issue–with Publisher you have the option to add a URL prefix to the current language which adds an additional segment, but is not included in EE's `{segment}` variables. So it seems with this set RR ignores that "first" segment as it is now working with this:
```
':any' => function($router, $wildcard) {
	$query = ee()->db->select('channel_id')
		->where('site_id', 1)
		->where('url_title', $wildcard->value)
		->where('publisher_status', 'open')
		->get('publisher_titles');

	$result = $query->row('channel_id');

	$router->setGlobal('test_results', $result);

	// is the current page a landing page?
	if ($result == 14) {
		$router->setTemplate('site/landing_page');
	// is the current page a confirmation page
	} else if ($result == 16) {
		$router->setTemplate('site/confirm_page');
	}
}```
