### ISSUE TITLE
Routing based on channel short name

### ISSUE THREAD

**Issue by akukral** [rsanchez/resource_router#30]
Is it possible and if so how would I route based on the channel short name of a wild card using the function? Basically using Resource Router to handle a landing page like this code:

	{if segment_1 != ''}
	
		{exp:channel:entries
			url_title="{last_segment}"
			disable="member_data|categories|pagination"
			dynamic="no"
		}

			{if channel_short_name == "single_pages"}
				{embed="site/_single_page"}
			{/if}

			{if channel_short_name == "microsites"}
				{embed="site/_microsite"}
			{/if}

			{if channel_short_name == "microsite_sub_pages"}
				{embed="site/_microsite_sub_page"}
			{/if}

		{/exp:channel:entries}

	{/if}

**Comment by akukral** [comment]
Sorry, I figured it out.

**Comment by akukral** [comment]
I figured out how to filter the the url titles but how would I use the call back for check the channel shot name if they are valid urls?

**Comment by rsanchez** [comment]
This should do it:

```php
$config['resource_router'] = array(
    ':any' => function($router, $wildcard) {
        // use real channel ids here
        $single_pages_channel_id = 1;
        $microsites_channel_id = 2;
        $microsite_sub_pages_channel_id = 3;

        $channels = array(
            $single_pages_channel_id,
            $microsites_channel_id,
            $microsite_sub_pages_channel_id,
        );

        if ($wildcard->isValidUrlTitle(array('channel_id' => $channels))) {
            if ($wildcard->getMeta('channel_id') == $single_pages_channel_id) {
                $router->setTemplate('site/_single_page');
            } elseif ($wildcard->getMeta('channel_id') == $microsites_channel_id) {
                $router->setTemplate('site/_microsite');
            } elseif ($wildcard->getMeta('channel_id') == $microsite_sub_pages_channel_id) {
                $router->setTemplate('site/_microsite_sub_page');
            }
        } else {
            $router->set404();
        }
    },
);
```

**Comment by akukral** [comment]
Wow, that worked great! Thank you for your help! It is greatly appreciated.
