### ISSUE TITLE
:pagination doesn't match pagination in segment 1

### ISSUE THREAD

**Issue by croxton** [rsanchez/resource_router#34]
...and if you use, say, `'(|P\d+)'` to match the homepage with optional pagination, setting a template seems to break channel:entries pagination. E.g.

    '(|P\d+)' => function($router, $wildcard="") {
        $router->setTemplate('blog'); // breaks pagination in segment 1
    },

The only reason I want to set a template there rather than allow EE to use the default template is so that subsequent rules are not processed. Ideally therefore I would like a way to stop rules being processed from that point on without having to set a template, say:

    $router->skipRoutes();

**Comment by rsanchez** [comment]
Would the best solution here to get :pagination working in segment 1?

**Comment by croxton** [comment]
That would be good, but wouldn't solve the problem that EE breaks pagination if you set a template for urls like `/`, `/P10` etc. Also `:url_title` matches pagination in segment 1.

Currently I'm using a workaround:

	/* set a flag to determine if further rules should be processed */
	':before' => function($router) {
		$router->continue = TRUE;
	},

	/* match homepage or segment_1 pagination */
	'(|P\d+)' => function($router, $wildcard="") {
		
		// can't set a template because it breaks EE pagination...
		// stop any other rules being processed, if this rule was matched
		$router->continue = FALSE;
	},

	/* match a url title in segment 1, but not pagination */
	':url_title' => function($router, $wildcard) {
		if ( ! $router->continue) return; 
		...
	}

	...[ lots of other rules ]...

	/* 404 for any other URL */
	'(.+)' => function($router, $wildcard) {
		if ( ! $router->continue) return;
		return $router->set404();
	}

I could use a negative lookahead in those last two rules to exclude pagination, but that seems inelegant. So it would be cool if a single call to `$router->skipRoutes();` (or similar) stopped the remaining rules in the `$router->routes` array from being processed.

**Comment by rsanchez** [comment]
Makes sense. Care to take a stab at it in the form of a pull request? I'd prefer the method to be called stopRouting.

**Comment by croxton** [comment]
Cool. Sure will do.
