### ISSUE TITLE
:pagination isn't working?

### ISSUE THREAD

**Issue by andyjh07** [rsanchez/resource_router#39]
Hi,

I'm using the following:

```
$config['resource_router'] = [
    'news-and-resources' => 'www/news-and-resources',
    'usa/news-and-resources' => 'www/news-and-resources',
    'cn/news-and-resources' => 'www/news-and-resources',
    'zh/news-and-resources' => 'www/news-and-resources',
    'usa/news-and-resources/:pagination' => 'www/news-and-resources',
];
```

The last should match a url of -

```
http://www.example.com/usa/news-and-resources/P3
```

But it just throws a 404 error, even though I _know_ it should load more entries.

What's causing this problem? I'm using Expression Engine 3.4.1

**Comment by rsanchez** [comment]
Let's see if it's your template causing the 404, or Resource Router. Reduce your `www/news-and-resources` template to:

```
{route_1}
```

See what it prints when you visit `http://www.example.com/usa/news-and-resources/P3` and whether it 404s or not.

**Comment by andyjh07** [comment]
Morning Rob,

I have already extensively tested it and reported a possible bug to EllisLab regarding this. Probably worth you reading my 2 threads below so you can see exactly what i've tried :)

https://ellislab.com/forums/viewthread/249382/

https://support.ellislab.com/bugs/detail/22420/Pagination-doesnt-work-properly-with-routes

I think it's a deep rooted issue with EE, but they're not getting back to me. See what you think

Thanks for the reply :)

Andy
