### ISSUE TITLE
Prematurely ending core_template_route hook execution

### ISSUE THREAD

**Issue by litzinger** [rsanchez/resource_router#49]
@rsanchez Is there a specific reason this end_script call was added? It's preventing any other add-on from using the core_template_route hook. In my case Publisher, which does quite a bit of work in that hook even if it doesn't change the actual template that should be used.

https://github.com/rsanchez/resource_router/blob/23494fd1ad27f621e6d2cc836a0ffe72db917beb/system/expressionengine/third_party/resource_router/ext.resource_router.php#L82

**Comment by rsanchez** [comment]
No idea, feel free to remove

**Comment by adrienne** [comment]
Fixed by #53 .
