### ISSUE TITLE
Hidden Templates

### ISSUE THREAD

**Issue by siebird** [rsanchez/resource_router#6]
Rob,

First time using resource router and I was banging my head for a couple minutes trying to figure out why the template was not being routed properly. So I duplicated the template without the hidden template indicator `_` and updated the route and everything works as expected. 

Not sure if this is as expected or a bug. Thanks for sharing man!

**Comment by croxton** [comment]
Just wanted to add to this: if you explicitly define the hidden template indicator in `config.php`, you CAN in fact route to hidden templates resource router:

    $config['hidden_template_indicator'] = '_';

**Comment by robsonsobral** [comment]
In case anybody is wondering why to route to a hidden template:

- Server Side Includes - on Apache, LiteSpeed, nginx, lighttpd and IIS, for example;
- Edge Side Includes - on Varnish, Squid and Mongrel ESI, for example.
